import pandas as pd 
import json
json_data='''
 [
     {"COMCOD":"1001", "COURSE NO.":"BIOF110" ,"COURSE TITLE":"BIOLOGY LABORATORY","CREDIT":{"L":"-","P":"2","U":"1"},"SEC":"P1","INSTRUCTOR IN CHARGE/Instructor":"Sayatani Chatterjee(RS)","ROOM":"3219","DAYS & HOURS":"F 6 7","MIDSEM DATE & SESSION:"", COMPRE DATE & SESSION:""}}
     {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Ramakrishnan S(RS),"ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}
     {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Jitendra kumar", "ROOM":"3219","DAYS & HOURS":"F 8 9","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}
     {"COMCOD":"","COURSE NO.":"","COURSE TITLE":"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCTOR-IN-CHARGE/Instructor":"Valluri Harsha Prabha(RS)","ROOM":"","DAYS & HOURS":"",MIDSEM DATE & SESSION:"", COMPRE DATE & SESSION:""}
     {"COMCOD"="", "COURSE NO.":"","COURSE TITLE":"","CREDIT":{"L":"","P":"","U":""},"SEC":"P3", "INSTRUCTOR-IN-CHARGE/Instructor":"Lourdes Jennifer S(RS)","ROOM":"3219","DAYS & HOURS":"M 1 2",MIDSEM DATE & SESSION:"", COMPRE DATE & SESSION:""}
     {"COMCOD"="", "COURSE NO.":"","COURSE TITLE":"","CREDIT":{"L":"","P":"","U":""},"SEC":"", "INSTRUCTOR-IN-CHARGE/Instructor":"B Vani","ROOM":"","DAYS & HOURS":"",MIDSEM DATE & SESSION:"", COMPRE DATE & SESSION:""}
     {"COMCOD"="", "COURSE NO.":"","COURSE TITLE":"","CREDIT":{"L":"","P":"","U":""},"SEC":"P4", "INSTRUCTOR-IN-CHARGE/Instructor":"Mukul Joshi","ROOM":"3219","DAYS & HOURS":"M 6 7",MIDSEM DATE & SESSION:"", COMPRE DATE & SESSION:""}
     {"COMCOD"="", "COURSE NO.":"","COURSE TITLE":"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCTOR-IN-CHARGE/Instructor":"Shiva Chaudhary(RS)","ROOM":"","DAYS & HOURS":"",MIDSEM DATE & SESSION:"", COMPRE DATE & SESSION:""}
     {"COMCOD"="", "COURSE NO.":"","COURSE TITLE":"","CREDIT":{"L":"","P":"","U":""},"SEC":"P5", "INSTRUCTOR-IN-CHARGE/Instructor":"Sandhya Amol Marathe","ROOM":"3219","DAYS & HOURS":"M 8 9",MIDSEM DATE & SESSION:"", COMPRE DATE & SESSION:""}
     {"COMCOD"="", "COURSE NO.":"","COURSE TITLE":"","CREDIT":{"L":"","P":"","U":""},"SEC":"", "INSTRUCTOR-IN-CHARGE/Instructor":"Ritu Jangir(RS)","ROOM":"","DAYS & HOURS":"", MIDSEM DATE & SESSION:"", COMPRE DATE & SESSION:""}
     {"COMCOD"="", "COURSE NO.":"","COURSE TITLE":"","CREDIT":{"L":"","P":"","U":""},"SEC:"P6", "INSTRUCTOR-IN-CHARGE/Instructor":"Meghana Tare","ROOM":"3219","DAYS & HOURS":"T 1 2",MIDSEM DATE & SESSION:"", COMPRE DATE & SESSION:""}
     {"COMCOD"="", "COURSE NO.":"","COURSE TITLE":"","CREDIT":{"L":"","P":"","U":""},"SEC":"", "INSTRUCTOR-IN-CHARGE/Instructor":"Hariharan J(RS)","ROOM":"","DAYS & HOURS":"",MIDSEM DATE & SESSION:"", COMPRE DATE & SESSION:""}
     {"COMCOD"="", "COURSE NO.":"","COURSE TITLE":"","CREDIT":{"L":"","P":"","U":""},"SEC:"P7", "INSTRUCTOR-IN-CHARGE/Instructor":"Anasuya Banerjee(RS)","ROOM":"3219","DAYS & HOURS":"T 6 7,"MIDSEM DATE & SESSION:"", COMPRE DATE & SESSION:""}
     {"COMCOD"="", "COURSE NO.":"","COURSE TITLE":"","CREDIT":{"L":"","P":"","U":""},"SEC":"", "INSTRUCTOR-IN-CHARGE/Instructor":"Shraddha Gupta(RS)","ROOM":"","DAYS & HOURS":"",MIDSEM DATE & SESSION:"", COMPRE DATE & SESSION:""}
     {"COMCOD"="", "COURSE NO.":"","COURSE TITLE":"","CREDIT":{"L":"","P":"","U":""},"SEC":"P8", "INSTRUCTOR-IN-CHARGE/Instructor":"RAJDEEP CHOWDHURY","ROOM":"3219","DAYS & HOURS":"T 8 9",MIDSEM DATE & SESSION:"", COMPRE DATE & SESSION:""}
     {"COMCOD"="", "COURSE NO.":"","COURSE TITLE":"","CREDIT":{"L":"","P":"","U":""},"SEC":"", "INSTRUCTOR-IN-CHARGE/Instructor":"Chakraborty Srinjoy Srabani(RS)","ROOM":"","DAYS & HOURS":"",MIDSEM DATE & SESSION:"", COMPRE DATE & SESSION:""}
     {"COMCOD"="", "COURSE NO.":"","COURSE TITLE":"","CREDIT":{"L":"","P":"","U":""},"SEC":"P9", "INSTRUCTOR-IN-CHARGE/Instructor":"Gujarati Sukriti Nisha(RS)","ROOM":"3219","DAYS & HOURS":"Th 6 7", MIDSEM DATE & SESSION:"", COMPRE DATE & SESSION:""}
     {"COMCOD"="", "COURSE NO.":"","COURSE TITLE":"","CREDIT":{"L":"","P":"","U":""},"SEC":"", "INSTRUCTOR-IN-CHARGE/Instructor":"Shristy Shreyar(RS)","ROOM":"","DAYS & HOURS":"",MIDSEM DATE & SESSION:"", COMPRE DATE & SESSION:""}
     {"COMCOD"="", "COURSE NO.":"","COURSE TITLE":"","CREDIT":{"L":"","P":"","U":""},"SEC":"P10", "INSTRUCTOR-IN-CHARGE/Instructo":"Farhanur Rahman(RS)","ROOM":"3219","DAYS & HOURS":"Th 8 9",MIDSEM DATE & SESSION:"", COMPRE DATE & SESSION:""}
     {"COMCOD"="", "COURSE NO.":"","COURSE TITLE":"","CREDIT":{"L":"","P":"","U":""},"SEC":"", "INSTRUCTOR-IN-CHARGE/Instructor":"Shelly Chauhan(RS)","ROOM":"","DAYS & HOURS":"",MIDSEM DATE & SESSION:"", COMPRE DATE & SESSION:""}
     {"COMCOD"="", "COURSE NO.":"","COURSE TITLE":"","CREDIT":{"L":"","P":"","U":""},"SEC":"P11", "INSTRUCTOR-IN-CHARGE/Instructor":"Balakumaran Chandrasekar","ROOM":"3219","DAYS & HOURS":"W 1 2",MIDSEM DATE & SESSION:"", COMPRE DATE & SESSION:""}
     {"COMCOD"="", "COURSE NO.":"","COURSE TITLE":"","CREDIT":{"L":"","P":"","U":""},"SEC":"", "INSTRUCTOR-IN-CHARGE/Instructor":"Saurabh Singh(RS)","ROOM":"","DAYS & HOURS":"",MIDSEM DATE & SESSION:"", COMPRE DATE & SESSION:""}
     {"COMCOD"="", "COURSE NO.":"","COURSE TITLE":"","CREDIT":{"L":"","P":"","U":""},"SEC":"P12", "INSTRUCTOR-IN-CHARGE/Instructor":"Prabhat Nath Jha","ROOM":"3219","DAYS & HOURS":"W 6 7",MIDSEM DATE & SESSION:"", COMPRE DATE & SESSION:""}
     {"COMCOD"="", "COURSE NO.":"","COURSE TITLE":"","CREDIT":{"L":"","P":"","U":""},"SEC":"",INSTRUCTOR-IN-CHARGE/Instructor":"Priya Gupta(RS)","ROOM":"","DAYS & HOURS":"",MIDSEM DATE & SESSION:"", COMPRE DATE & SESSION:""}
     {"COMCOD"="", "COURSE NO.":"","COURSE TITLE":"","CREDIT":{"L":"","P":"","U":""},"SEC":"P13", "INSTRUCTOR-IN-CHARGE/Instructor":"Sushama Biswas(RS)","ROOM":"3219","DAYS & HOURS":"W 8 9",MIDSEM DATE & SESSION:"", COMPRE DATE & SESSION:""}
    
    {"COMCOD":"1002","COURSE NO.:"BIO F111","COURSE TITLE":"GENERAL BIOLOGY","CREDIT"{"L":"3","P":"-","U":"3","SEC":"L1",INSTRUCTOR-IN-CHARGE/Instructor:"SHIBASHISH CHOWDHURY","ROOM":"5102","DAYS & HOURS":"T Th F2","MIDSEM DATE & SESSION:"09/10 FN2","COMPE DATE & SESSION":14/12 AN}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Syamantak Majumder","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Pankaj Kumar Sharma","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Vishal Saxena","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"L2","INSTRUCOR-IN-CHARGE/Instructor":"Syamantak Majumder","ROOM":"5106","DAYS & HOURS":"T Th F 4","MIDSEM DATE & SESSION":"09/10 FN2","COMPRE DATE & SESSION":"14/12 AN"}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Pankaj Kumar Sharma","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Vishal Saxena","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"Tutorial","CREDIT":{"L":"","P":"","U":""},"SEC":"T1","INSTRUCOR-IN-CHARGE/Instructor":"Shashi Prakash Singh","ROOM":"6157","DAYS & HOURS":"F 1","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"T2","INSTRUCOR-IN-CHARGE/Instructor":"Uma S Dubey","ROOM":"6158","DAYS & HOURS":"F 1","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"T3","INSTRUCOR-IN-CHARGE/Instructor":"Shashi Prakash Singh","ROOM":"6153","DAYS & HOURS":T 7"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"T4","INSTRUCOR-IN-CHARGE/Instructor":"Syamantak Majumder","ROOM":"6103","DAYS & HOURS":"T 7","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"T5","INSTRUCOR-IN-CHARGE/Instructor":"Pankaj Kumar Sharma","ROOM":"6104","DAYS & HOURS":"T 7","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"T6","INSTRUCOR-IN-CHARGE/Instructor":"Ashis Kumar Das","ROOM":"6154","DAYS & HOURS":"T 7","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"T7","INSTRUCOR-IN-CHARGE/Instructor":"Soumitra Ghosh","ROOM":"6157","DAYS & HOURS":"T 7","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"T8","INSTRUCOR-IN-CHARGE/Instructor":"P R Deepa","ROOM":"6153","DAYS & HOURS":"W 1","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"T9","INSTRUCOR-IN-CHARGE/Instructor":"Uma S Dubey","ROOM":"6154","DAYS & HOURS":"W 1","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"T10","INSTRUCOR-IN-CHARGE/Instructor":"Sudeshna Mukherjee","ROOM":"6157","DAYS & HOURS":"W 1","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"T11","INSTRUCOR-IN-CHARGE/Instructor":"Soumitra Ghosh","ROOM":"6158","DAYS & HOURS":"W 1","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"T12","INSTRUCOR-IN-CHARGE/Instructor":"Shibasish Chowdhury","ROOM":"6159","DAYS & HOURS":"W 1","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"T13","INSTRUCOR-IN-CHARGE/Instructor":"Vishal Saxena","ROOM":"6103","DAYS & HOURS":"W 1","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}
    
    {"COMCOD":"1004","COURSE NO.":"BITS F111", "COURSE TITLE:"THERMODYNAMICS","CREDIT":{"L":"3","P":"-","U":"3"},"SEC":"L1","INSTRUCOR-IN-CHARGE/Instructor":"Manoj Kumar Soni","ROOM":"5102","DAYS & HOURS":"M W 3 Th 9","MIDSEM DATE & SESSION":"03/10 FN2","COMPRE DATE & SESSION":"02/12 AN"}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"L2","INSTRUCOR-IN-CHARGE/Instructor":"SACHIN ULHASRAO BELGAMWAR","ROOM":"5102","DAYS & HOURS":"T Th F 3","MIDSEM DATE & SESSION":"03/10 FN2","COMPRE DATE & SESSION":"02/12 AN"}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"L3","INSTRUCOR-IN-CHARGE/Instructor":"Amit Jain","ROOM":"5102","DAYS & HOURS":"T Th F 6","MIDSEM DATE & SESSION":"03/10 FN2","COMPRE DATE & SESSION":"02/12 AN"}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"Tutorial","CREDIT":{"L":"","P":"","U":""},"SEC":"T1","INSTRUCOR-IN-CHARGE/Instructor":"Pradipta Chattopadhyay","ROOM":"1202","DAYS & HOURS":"F 1","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"T2","INSTRUCOR-IN-CHARGE/Instructor":"Naveen P. T.(RS)","ROOM":"6107","DAYS & HOURS":"F 1","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"T3","INSTRUCOR-IN-CHARGE/Instructor":"Amit Jain","ROOM":"1226","DAYS & HOURS":"F 1","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"T4","INSTRUCOR-IN-CHARGE/Instructor":"Biswadip Shome","ROOM":"1223","DAYS & HOURS":"F 1","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"T5","INSTRUCOR-IN-CHARGE/Instructor":"Bhanu Vardhan Reddy Kuncharam","ROOM":"6159","DAYS & HOURS":"F 1","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"T6","INSTRUCOR-IN-CHARGE/Instructor":"Priya Christina Sande","ROOM":"1201","DAYS & HOURS":"F 1","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"T7","INSTRUCOR-IN-CHARGE/Instructor":"Manoj Kumar Soni","ROOM":"6102","DAYS & HOURS":"M 1","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"T8","INSTRUCOR-IN-CHARGE/Instructor":"Indresh Kumar","ROOM":"6153","DAYS & HOURS":"M 1","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"T9","INSTRUCOR-IN-CHARGE/Instructor":"Nancy Maurya(RS)","ROOM":"1226","DAYS & HOURS":"M 1","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"T10","INSTRUCOR-IN-CHARGE/Instructor":"Pritam Kumar Jana","ROOM":"6154","DAYS & HOURS":"M 1","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"T11","INSTRUCOR-IN-CHARGE/Instructor":"Faizan Mohammad Rashid","ROOM":"2207","DAYS & HOURS":"M 1","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"T12","INSTRUCOR-IN-CHARGE/Instructor":"Priya Christina Sande","ROOM":"1205","DAYS & HOURS":"M 1","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"T13","INSTRUCOR-IN-CHARGE/Instructor":"Sachin Ulhasrao Belgamwar","ROOM":"1232","DAYS & HOURS":"T 8","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"T14","INSTRUCOR-IN-CHARGE/Instructor":"Indresh Kumar","ROOM":"6153","DAYS & HOURS":"T 8","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"T15","INSTRUCOR-IN-CHARGE/Instructor":"Sajal Mukherjee","ROOM":"1203","DAYS & HOURS":"T 8","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"T16","INSTRUCOR-IN-CHARGE/Instructor":"Pritam Kumar Jana","ROOM":"1205","DAYS & HOURS":"T 8","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"T17","INSTRUCOR-IN-CHARGE/Instructor":"Arpan Das","ROOM":"6154","DAYS & HOURS":"T 8","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"T18","INSTRUCOR-IN-CHARGE/Instructor":"Tanmoy Mondal","ROOM":"6157","DAYS & HOURS":"T 8","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"T19","INSTRUCOR-IN-CHARGE/Instructor":"Etika Krishna Chaitanya","ROOM":"1231","DAYS & HOURS":"Th 1","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"T20","INSTRUCOR-IN-CHARGE/Instructor":"Amit Jain","ROOM":"6157","DAYS & HOURS":"Th 1","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"T21","INSTRUCOR-IN-CHARGE/Instructor":"Faizan Mohammad Rashid","ROOM":"1203","DAYS & HOURS":"Th 1","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"T22","INSTRUCOR-IN-CHARGE/Instructor":"Shyam Sunder Yadav","ROOM":"1226","DAYS & HOURS":"Th 1","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"T23","INSTRUCOR-IN-CHARGE/Instructor":"Biswadip Shome","ROOM":"1227","DAYS & HOURS":"Th 1","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}

    {"COMCOD":"1005","COURSE NO.":"BITS F1112", "COURSE TITLE:"TECHNICAL REPORT WRITING","CREDIT":{"L":"2","P":"-","U":"2"},"SEC":"L1","INSTRUCOR-IN-CHARGE/Instructor":"Sanjiv Kumar Choudhary","ROOM":"5102","DAYS & HOURS":"M W 9","MIDSEM DATE & SESSION":"09/10 AN2","COMPRE DATE & SESSION":"16/12 AN"}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Sanjiv Kumar Choudhary","ROOM":"6152","DAYS & HOURS":"M W 6","MIDSEM DATE & SESSION":"09/10 AN2","COMPRE DATE & SESSION":"16/12 AN"}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Paul Mathew","ROOM":"6151","DAYS & HOURS":"M W 7","MIDSEM DATE & SESSION":"09/10 AN2","COMPRE DATE & SESSION":"16/12 AN"}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"SUSHILA SHEKHAWAT","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Ruchika Sharma(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Kirti Singh(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Pooja Chatterjee(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Vibha(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Asita A.(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Swati(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Sonika(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Kadam Onkar Rajendra(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Manasi Panwar(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Pradeep Bailwal(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Pranjal Aarav(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Sangeeta Sharma","ROOM":"6151","DAYS & HOURS":"M W 8","MIDSEM DATE & SESSION":"09/10 AN2","COMPRE DATE & SESSION":"16/12 AN"}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Virendra Singh Nirban","ROOM":"6151","DAYS & HOURS":"T Th 7","MIDSEM DATE & SESSION":"09/10 AN2","COMPRE DATE & SESSION":"16/12 AN"}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Prateek","ROOM":"6152","DAYS & HOURS":"T Th 8","MIDSEM DATE & SESSION":"09/10 AN2","COMPRE DATE & SESSION":"16/12 AN"}}

    {"COMCOD":"1006","COURSE NO.":"CHEM F110", "COURSE TITLE:"CHEMISTRY LABORATORY","CREDIT":{"L":"","P":"2","U":"1"},"SEC":"P1","INSTRUCOR-IN-CHARGE/Instructor":"Paritosh Shukla","ROOM":"3115","DAYS & HOURS":F 1 2","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Susmita Pradhan(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Mainika Verma(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"P2","INSTRUCOR-IN-CHARGE/Instructor":"PRASHANT UDAY MANOHAR","ROOM":"3115","DAYS & HOURS":"F 3 4","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Shubhangi Sharma(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Pinki(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"P3","INSTRUCOR-IN-CHARGE/Instructor":"Annu(RS)","ROOM":"3115","DAYS & HOURS":"F 6 7","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Ritu Rani(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Nitika(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Nancy(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"P4","INSTRUCOR-IN-CHARGE/Instructor":"Ajay Kumar Sah","ROOM":"3115","DAYS & HOURS":"F 8 9","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Sakshi Bajaj(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Khushika(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"P5","INSTRUCOR-IN-CHARGE/Instructor":"Paritosh Shukla","ROOM":"3115","DAYS & HOURS":"M 1 2","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Ritu Kumari(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Arpit(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"P6","INSTRUCOR-IN-CHARGE/Instructor":"Prekshi Gupta(RS)","ROOM":"3115","DAYS & HOURS":"M 3 4","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Bharti Khungar","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Nitika(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"P7","INSTRUCOR-IN-CHARGE/Instructor":"Reena Jangir(RS)","ROOM":"3115","DAYS & HOURS":"M  6 7","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Satyajit Patra","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Pragati Shrivastava(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"P8","INSTRUCOR-IN-CHARGE/Instructor":"Madhushree Sarkar","ROOM":"3115","DAYS & HOURS":"M  8 9","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Priyanka Bhardwaj(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Ritu Kumari(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"P9","INSTRUCOR-IN-CHARGE/Instructor":"Nidhi(RS)","ROOM":"3115","DAYS & HOURS":"S  1 2","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Prashant Choubey(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Tank Disha Harsukhbhai(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"P10","INSTRUCOR-IN-CHARGE/Instructor":"Reena Jangir(RS)","ROOM":"3115","DAYS & HOURS":"S  3 4","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Khushika(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Pinki(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"P11","INSTRUCOR-IN-CHARGE/Instructor":"Gadekar Amol Bhagwanrao(RS)","ROOM":"3115","DAYS & HOURS":"S   6 7","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Shruti Soni(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Vani Dhyani(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"P12","INSTRUCOR-IN-CHARGE/Instructor":"Heena(RS)","ROOM":"3115","DAYS & HOURS":"S  8 9","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Anakshi Boruah(RS)","ROOM":"3115","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Tarun Jangir(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Samya Suvra Datta(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"P13","INSTRUCOR-IN-CHARGE/Instructor":"Satyajit Patra","ROOM":"3115","DAYS & HOURS":"T  1 2","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Tank Disha Harsukhbhai(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Susmita Pradhan(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"P14","INSTRUCOR-IN-CHARGE/Instructor":"Astha Gupta(RS)","ROOM":"3115","DAYS & HOURS":"T  3 4","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Ram Kinkar Roy","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Shruti Soni(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"P15","INSTRUCOR-IN-CHARGE/Instructor":"Prashant Uday Manohar","ROOM":"3115","DAYS & HOURS":"T 6 7","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Borade Somnath Arjun(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Meenu(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"P16","INSTRUCOR-IN-CHARGE/Instructor":"Madhushree Sarkar","ROOM":"3115","DAYS & HOURS":"T 8 9","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Priyanka Bhardwaj(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Arun Patel(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"P17","INSTRUCOR-IN-CHARGE/Instructor":"Prekshi Gupta(RS)","ROOM":"3115","DAYS & HOURS":"Th 1 2","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Shubhangi Sharma(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Tarun Jangir(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"P18","INSTRUCOR-IN-CHARGE/Instructor":"Amrita Chakraborty","ROOM":"3115","DAYS & HOURS":"Th 3 4","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Ritu Rani(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Nidhi(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"P19","INSTRUCOR-IN-CHARGE/Instructor":"Ram Kinkar Roy","ROOM":"3115","DAYS & HOURS":"Th 6 7","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Meenu(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Anakshi Boruah(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"P20","INSTRUCOR-IN-CHARGE/Instructor":"Gadekar Amol Bhagwanrao(RS)","ROOM":"3115","DAYS & HOURS":"Th 8 9","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Ajay Kumar Sah","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Sakshi Bajaj(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"P21","INSTRUCOR-IN-CHARGE/Instructor":"Surojit Pande","ROOM":"3115","DAYS & HOURS":"W 1 2","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Nidhi(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Prashant Choubey(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"P22","INSTRUCOR-IN-CHARGE/Instructor":"Bibhas Ranjan Sarkar","ROOM":"3115","DAYS & HOURS":"W 3 4","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Arun Patel(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Sakshi Kushwaha(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"P23","INSTRUCOR-IN-CHARGE/Instructor":"Astha Gupta(RS)","ROOM":"3115","DAYS & HOURS":"W 6 7","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Borade Somnath Arjun(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Arpit(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Antima Saini(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"P24","INSTRUCOR-IN-CHARGE/Instructor":"Heena(RS)","ROOM":"3115","DAYS & HOURS":"W 8 9","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Annu(RS)","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Surojit Pande","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}

    
    {"COMCOD":"1007","COURSE NO.":"CHEM F111", "COURSE TITLE:"GENERAL CHEMISTRY","CREDIT":{"L":"3","P":"","U":"3"},"SEC":"L1","INSTRUCOR-IN-CHARGE/Instructor":"PARTHA SARATHI ADDY","ROOM":"5105","DAYS & HOURS":"T Th F 2","MIDSEM DATE & SESSION":"04/10 FN2","COMPRE DATE & SESSION":"04/12 AN"}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Madhushree Sarkar","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Rajeev Sakhuja","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Partha Sarathi Addy","ROOM":"5105","DAYS & HOURS":"T Th F 4","MIDSEM DATE & SESSION":"04/10 FN2","COMPRE DATE & SESSION":"05/12 AN"}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Madhushree Sarkar","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Rajeev Sakhuja","ROOM":"","DAYS & HOURS":"","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Paritosh Shukla","ROOM":"2204","DAYS & HOURS":"T 7","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Shamik Chakraborty","ROOM":"6107","DAYS & HOURS":"T 7","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Partha Sarathi Addy","ROOM":"6109","DAYS & HOURS":"T 7","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Ram Kinkar Roy","ROOM":"6160","DAYS & HOURS":"T 7","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Saumi Ray","ROOM":"6161","DAYS & HOURS":"T 7","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Prashant Uday Manohar","ROOM":"6153","DAYS & HOURS":"Th 7","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Paritosh Shukla","ROOM":"2204","DAYS & HOURS":"Th 7","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Madhushree Sarkar","ROOM":"6152","DAYS & HOURS":"Th 7","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Inamur Rahaman Laskar","ROOM":"6163","DAYS & HOURS":"Th 7","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Ram Kinkar Roy","ROOM":"6160","DAYS & HOURS":"W 1","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Saumi Ray","ROOM":"6161","DAYS & HOURS":"W 1","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}
    {"COMCOD":"","COURSE NO.":"", "COURSE TITLE:"","CREDIT":{"L":"","P":"","U":""},"SEC":"","INSTRUCOR-IN-CHARGE/Instructor":"Inamur Rahaman Laskar","ROOM":"6105","DAYS & HOURS":"W 1","MIDSEM DATE & SESSION":"","COMPRE DATE & SESSION":""}
]
'''
data=[pd.json_normalize(json.loads(line))
for line in json_data.strip().split('\n')]
df=pd.concat(data, ignore_index=True)
print(df)